made changes

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -50,15 +50,14 @@ jobs:
         - name: Terraform Plan
           id: plan
           run: terraform plan -no-color -input=false -out planfile
-          continue-on-error: true 
 
-        - name: Terraform Plan Status 
+        - name: Terraform Plan Status
           if: steps.plan.outcome == 'failure'
-          run: exit 1
+          run: echo "Terraform Plan failed. Exiting." && exit 1
 
         - name: Terraform Apply
           id: apply
-          if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+          if: steps.plan.outcome == 'success' && github.ref == 'refs/heads/main' && github.event_name == 'push'
           run: terraform apply -auto-approve -input=false -parallelism=1 planfile
 
 
